services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-readme-local
    environment:
      POSTGRES_USER: ${DB_USERNAME:-readme_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-readme_password}
      POSTGRES_DB: ${DB_NAME:-readme_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-readme-local:/var/lib/postgresql/data
    networks:
      - internal-net-readme-local

#==============================
# NETWORK CONFIGURATION
#==============================
networks:
  internal-net-readme-local:
    name: internal-net-readme-local
    driver: bridge

#==============================
# VOLUME STORAGES
#==============================
volumes:
  postgres-data-readme-local:
    name: postgres-data-readme-local
