server:
  port: 8080

spring:
  application:
    name: readme-ai

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY:dummy_key_for_startup_purposes}
        project-id: ${GOOGLE_CLOUD_PROJECT:dummy_project_id_for_startup}
        location: ${GOOGLE_CLOUD_LOCATION:us-central1}
        embedding:
          api-key: ${GEMINI_API_KEY:dummy_key_for_startup_purposes}
          project-id: ${GOOGLE_CLOUD_PROJECT:dummy_project_id_for_startup}
          location: ${GOOGLE_CLOUD_LOCATION:us-central1}
          options:
            model: text-embedding-004
            output-dimensionality: 768
        chat:
          options:
            model: gemini-3.5-flash
            temperature: 0.5

    vectorstore:
      pgvector:
        dimension: 768
        distance-type: COSINE_DISTANCE
        index-type: HNSW
